return {
  'andweeb/presence.nvim',
  'ap/vim-css-color',
  'tpope/vim-abolish',
  'tpope/vim-repeat',
  require 'custom.plugins.comment',
  require 'custom.plugins.dressing',
  require 'custom.plugins.fugitive',
  require 'custom.plugins.harpoon',
  require 'custom.plugins.inc-rename',
  require 'custom.plugins.live-server',
  require 'custom.plugins.nvim-colorizer',
  require 'custom.plugins.nvim-emmet',
  require 'custom.plugins.nvim-ts-autotag',
  require 'custom.plugins.peek',
  require 'custom.plugins.schemastore',
  require 'custom.plugins.typescript-tools',
  require 'custom.plugins.undotree',
  require 'custom.plugins.usage',
  require 'custom.plugins.vim-airline',
}
